// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkhOBIEaIdLoMNSLV3DYGOCZ_STMzwlIE',
    appId: '1:519570495284:android:624734bdffd0d9ab763761',
    messagingSenderId: '519570495284',
    projectId: 'stringeesample-f3e03',
    databaseURL:
        'https://stringeesample-f3e03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stringeesample-f3e03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZN8yUeUtkSL8RoW8X44mABZrWEYxSBY',
    appId: '1:519570495284:ios:da98b23d6bb63e80763761',
    messagingSenderId: '519570495284',
    projectId: 'stringeesample-f3e03',
    databaseURL:
        'https://stringeesample-f3e03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stringeesample-f3e03.appspot.com',
    iosBundleId: 'com.stringee.flutter.sample',
  );
}
