// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgjtRv_lkgunSQv6ZOrntzqxKof0yHakg',
    appId: '1:487302158808:web:ffb4746f4d2b23251e3aad',
    messagingSenderId: '487302158808',
    projectId: 'chat-notification-sample',
    authDomain: 'chat-notification-sample.firebaseapp.com',
    storageBucket: 'chat-notification-sample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGQKB0cHgju3C1ZQmIZvkO8PjrbzyE8d4',
    appId: '1:487302158808:android:e79b4227c6a8f5a91e3aad',
    messagingSenderId: '487302158808',
    projectId: 'chat-notification-sample',
    storageBucket: 'chat-notification-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg-UkiY4uP2sJjjV9VjqD4hl6U4ayZmcQ',
    appId: '1:487302158808:ios:119d542486ef803d1e3aad',
    messagingSenderId: '487302158808',
    projectId: 'chat-notification-sample',
    storageBucket: 'chat-notification-sample.appspot.com',
    iosClientId: '487302158808-nt8iiem5ffsfjavlfff75ip8qfgan3j6.apps.googleusercontent.com',
    iosBundleId: 'com.stringee.CallkitSample',
  );
}
